In [3]:
!mv /Users/shzh8108/Downloads/Amphibians_on_NPS_Lands_20231201.csv .

In [6]:
import pandas as pd

pd.set_option('display.max_columns', 50)

df = pd.read_csv("./Amphibians_on_NPS_Lands_20231201.csv")

print(len(df))

df.head()

3472

,Park_Code,Park_Name,IM_Network,CASC_Region,State,TSN,Order,Family,Scientific_Name,Common_Names,Verified_Date,Park_OccurrenceStatus,Notes,Verified_Source,Park_Synonyms,NPSpecies_Occurrence,NPSpecies_OccTag,Abundance,Nativeness,GRank,SRank,IUCNRank
0,ABLI,Abraham Lincoln Birthplace National Historical...,CUPN,NE,KY,173520,Anura,Hylidae,Acris crepitans,"Northern Cricket Frog, Eastern Cricket Frog",2020-09-08,Present,NaN,https://irma.nps.gov/DataStore/DownloadFile/42...,Acris crepitans crepitans,Present,NaN,Common,Native,G5,KY: S5,LC
1,ABLI,Abraham Lincoln Birthplace National Historical...,CUPN,NE,KY,208204,Caudata,Ambystomatidae,Ambystoma barbouri,Streamside Salamander,2020-09-08,Adjacent,NaN,https://irma.nps.gov/DataStore/DownloadFile/42...,NaN,Not In Park,Adjacent,NaN,Native,G4,KY: S4,NT
2,ABLI,Abraham Lincoln Birthplace National Historical...,CUPN,NE,KY,173598,Caudata,Ambystomatidae,Ambystoma jeffersonianum,Jefferson Salamander,2020-09-08,Adjacent,Expected but not observed,https://irma.nps.gov/DataStore/DownloadFile/42...,NaN,Unconfirmed,NaN,NaN,Native,G4,KY: S4,LC
3,ABLI,Abraham Lincoln Birthplace National Historical...,CUPN,NE,KY,173590,Caudata,Ambystomatidae,Ambystoma maculatum,Spotted Salamander,2020-09-08,Adjacent,Expected but not observed,https://irma.nps.gov/DataStore/DownloadFile/42...,NaN,Unconfirmed,NaN,NaN,Native,G5,KY: S5,LC
4,ABLI,Abraham Lincoln Birthplace National Historical...,CUPN,NE,KY,173591,Caudata,Ambystomatidae,Ambystoma opacum,Marbled Salamander,2020-09-08,Adjacent,NaN,https://irma.nps.gov/DataStore/DownloadFile/42...,NaN,Not In Park,Adjacent,NaN,Native,G5,KY: S5,LC

In [8]:
# How many species per park?

species_by_park = df.groupby('Park_Code').agg({'Scientific_Name': ['count', 'nunique']})

          Scientific_Name
                    count nunique
Park_Code
ABLI                   30      30
ACAD                   15      15
AGFO                    7       7
ALFL                   13      13
ALPO                   25      25
...                   ...     ...
YELL                    6       6
YOSE                   13      13
YUCH                    1       1
YUHO                    5       5
ZION                    7       7

[286 rows x 2 columns]